// Portfolio copy in the five supported languages.
window.portfolioCopy = {
  "es": {
    "new.creativeNote": "Ideas, apuntes y trabajo diario",
    "ui.skip": "Saltar al contenido",
    "ui.language": "Idioma",
    "ui.appearance": "Apariencia",
    "ui.light": "Claro",
    "ui.dark": "Oscuro",
    "ui.close": "Cerrar vídeo",
    "new.letsTalk": "Hablemos",
    "new.discipline": "PUBLICIDAD / RELACIONES PÚBLICAS",
    "new.heroText": "Graduada en la UPF. He trabajado en cuentas, comunicación y contenidos, especialmente en el sector de la salud.",
    "new.meet": "Conóceme",
    "new.heroFooter": "Barcelona / Publicidad y comunicación",
    "new.scroll": "Sigue explorando",
    "new.aboutHeading1": "Un poco",
    "new.aboutHeading2": "sobre mí",
    "new.aboutLead": "He pasado por agencias, equipos de comunicación y eventos. En cada puesto he aprendido algo distinto.",
    "new.aboutText": "Soy graduada en Publicidad y Relaciones Públicas por la Universitat Pompeu Fabra. He trabajado en comunicación de salud, relaciones con medios, redes sociales y coordinación de eventos.",
    "new.aboutPersonal": "Mi experiencia va desde preparar una presentación y coordinar un briefing hasta escribir para redes o hablar con medios. Me gusta trabajar con otras personas y cuidar los detalles de cada entrega.",
    "new.presentation": "En primera persona",
    "new.videoEyebrow": "PRESENTACIÓN",
    "new.videoHeading1": "Hola,",
    "new.videoHeading2": "soy Sara",
    "new.discover": "Descubre mi experiencia",
    "video.soon": "Próximamente",
    "video.ready": "Vídeo de presentación",
    "video.pending": "Aquí estará mi vídeo de presentación. Hasta entonces, puedes conocer mi experiencia un poco más abajo.",
    "video.description": "Mi forma de entender la comunicación, lo que me mueve y lo que puedo aportar a tu próximo proyecto. Te lo cuento en primera persona.",
    "video.play": "Ver presentación",
    "video.title": "Presentación de SARA",
    "video.error": "No se ha podido cargar el vídeo. Inténtalo de nuevo más tarde.",
    "new.experienceHeading1": "Dónde he",
    "new.experienceHeading2": "trabajado",
    "new.experienceIntro": "Cuentas, contenidos, medios y eventos. Estos son los equipos de los que he formado parte.",
    "new.roleSanno": "Asistente de Comunicación",
    "new.roleParadigma": "Ejecutiva de Cuentas Junior",
    "new.roleTicket": "Gestión de acreditación",
    "new.roleEnglish": "Profesora de inglés",
    "new.jobOlixir": "Gestión de proyectos en el sector de la salud, coordinación de briefings, elaboración de materiales y presentaciones, gestión administrativa y financiera y apoyo en la revisión de contenido sanitario.",
    "new.jobSanno": "Creación y planificación de contenidos para redes sociales y newsletter, elaboración de materiales y presentaciones, contacto con colaboradores, apoyo en eventos y análisis del mercado.",
    "new.jobLewis": "Contacto con medios, redacción de artículos de opinión y contenido para redes sociales, organización y gestión de proyectos y gestión administrativa.",
    "new.jobParadigma": "Recepción de briefings, gestión de cuentas en el sector de la salud, supervisión de proyectos y gestión logística.",
    "new.jobTicket": "Coordinación del equipo de acreditación de la sección VIP en el Palau Sant Jordi.",
    "new.jobDiari": "Organización semanal de contenido y coordinación de redes sociales.",
    "new.jobEnglish": "Planificación y coordinación de actividades, cuidado de niños de 4 a 8 años y organización administrativa.",
    "new.educationHeading1": "Lo que he",
    "new.educationHeading2": "estudiado",
    "new.courseProtocol": "Protocolo y Comunicación",
    "new.courseVideo": "Realización Audiovisual para Redes Sociales",
    "new.skillsHeading": "Con qué trabajo",
    "new.skillStrategy": "Organización",
    "new.skillStrategyText": "Gestión de proyectos, coordinación de equipos, atención al detalle y resolución de problemas.",
    "new.skillCreative": "Diseño y contenido",
    "new.skillCommunication": "Comunicación",
    "new.skillCommunicationText": "Oratoria, relaciones con medios, trabajo en equipo y creación de contenidos.",
    "new.contactHeading1": "¿Hablamos?",
    "new.contactHeading2": "Escríbeme",
    "new.backTop": "Volver arriba"
  },
  "ca": {
    "new.creativeNote": "Idees, apunts i feina diària",
    "ui.skip": "Saltar al contingut",
    "ui.language": "Idioma",
    "ui.appearance": "Aparença",
    "ui.light": "Clar",
    "ui.dark": "Fosc",
    "ui.close": "Tancar vídeo",
    "new.letsTalk": "Parlem",
    "new.discipline": "PUBLICITAT / RELACIONS PÚBLIQUES",
    "new.heroText": "Graduada a la UPF. He treballat en comptes, comunicació i continguts, especialment en el sector de la salut.",
    "new.meet": "Coneix-me",
    "new.heroFooter": "Barcelona / Publicitat i comunicació",
    "new.scroll": "Segueix explorant",
    "new.aboutHeading1": "Una mica",
    "new.aboutHeading2": "sobre mi",
    "new.aboutLead": "He passat per agències, equips de comunicació i esdeveniments. A cada lloc he après alguna cosa diferent.",
    "new.aboutText": "Soc graduada en Publicitat i Relacions Públiques per la Universitat Pompeu Fabra. He treballat en comunicació de salut, relacions amb mitjans, xarxes socials i coordinació d’esdeveniments.",
    "new.aboutPersonal": "La meva experiència va de preparar una presentació i coordinar un briefing a escriure per a xarxes o parlar amb mitjans. M’agrada treballar amb altres persones i cuidar els detalls de cada entrega.",
    "new.presentation": "En primera persona",
    "new.videoEyebrow": "PRESENTACIÓ",
    "new.videoHeading1": "Hola,",
    "new.videoHeading2": "soc la Sara",
    "new.discover": "Descobreix la meva experiència",
    "video.soon": "Properament",
    "video.ready": "Vídeo de presentació",
    "video.pending": "Aquí hi haurà el meu vídeo de presentació. Mentrestant, pots conèixer la meva experiència una mica més avall.",
    "video.description": "La meva manera d’entendre la comunicació, el que em mou i el que puc aportar al teu proper projecte. T’ho explico en primera persona.",
    "video.play": "Veure presentació",
    "video.title": "Presentació de la SARA",
    "video.error": "No s’ha pogut carregar el vídeo. Torna-ho a provar més tard.",
    "new.experienceHeading1": "On he",
    "new.experienceHeading2": "treballat",
    "new.experienceIntro": "Comptes, continguts, mitjans i esdeveniments. Aquests són els equips dels quals he format part.",
    "new.roleSanno": "Assistent de Comunicació",
    "new.roleParadigma": "Executiva de Comptes Júnior",
    "new.roleTicket": "Gestió d’acreditació",
    "new.roleEnglish": "Professora d’anglès",
    "new.jobOlixir": "Gestió de projectes en el sector de la salut, coordinació de briefings, elaboració de materials i presentacions, gestió administrativa i financera i suport en la revisió de contingut sanitari.",
    "new.jobSanno": "Creació i planificació de continguts per a xarxes socials i newsletter, elaboració de materials i presentacions, contacte amb col·laboradors, suport en esdeveniments i anàlisi del mercat.",
    "new.jobLewis": "Contacte amb mitjans, redacció d’articles d’opinió i contingut per a xarxes socials, organització i gestió de projectes i gestió administrativa.",
    "new.jobParadigma": "Recepció de briefings, gestió de comptes en el sector de la salut, supervisió de projectes i gestió logística.",
    "new.jobTicket": "Coordinació de l’equip d’acreditació de la secció VIP al Palau Sant Jordi.",
    "new.jobDiari": "Organització setmanal de contingut i coordinació de xarxes socials.",
    "new.jobEnglish": "Planificació i coordinació d’activitats, cura d’infants de 4 a 8 anys i organització administrativa.",
    "new.educationHeading1": "El que he",
    "new.educationHeading2": "estudiat",
    "new.courseProtocol": "Protocol i Comunicació",
    "new.courseVideo": "Realització Audiovisual per a Xarxes Socials",
    "new.skillsHeading": "Amb què treballo",
    "new.skillStrategy": "Organització",
    "new.skillStrategyText": "Gestió de projectes, coordinació d’equips, atenció al detall i resolució de problemes.",
    "new.skillCreative": "Disseny i contingut",
    "new.skillCommunication": "Comunicació",
    "new.skillCommunicationText": "Oratòria, relacions amb mitjans, treball en equip i creació de continguts.",
    "new.contactHeading1": "Parlem?",
    "new.contactHeading2": "Escriu-me",
    "new.backTop": "Tornar a dalt"
  },
  "en": {
    "new.creativeNote": "Ideas, notes and everyday work",
    "ui.skip": "Skip to content",
    "ui.language": "Language",
    "ui.appearance": "Appearance",
    "ui.light": "Light",
    "ui.dark": "Dark",
    "ui.close": "Close video",
    "new.letsTalk": "Let’s talk",
    "new.discipline": "ADVERTISING / PUBLIC RELATIONS",
    "new.heroText": "UPF graduate. I have worked in accounts, communication and content, particularly in healthcare.",
    "new.meet": "Meet me",
    "new.heroFooter": "Barcelona / Advertising and communication",
    "new.scroll": "Keep exploring",
    "new.aboutHeading1": "A little",
    "new.aboutHeading2": "about me",
    "new.aboutLead": "I have worked in agencies, communications teams and events. Each role has taught me something different.",
    "new.aboutText": "I hold a degree in Advertising and Public Relations from Universitat Pompeu Fabra. My experience includes healthcare communication, media relations, social media and event coordination.",
    "new.aboutPersonal": "My experience ranges from preparing presentations and coordinating briefs to writing for social media and speaking with journalists. I enjoy working with others and taking care of the details in each delivery.",
    "new.presentation": "In my own words",
    "new.videoEyebrow": "INTRODUCTION",
    "new.videoHeading1": "Hi,",
    "new.videoHeading2": "I’m Sara",
    "new.discover": "Explore my experience",
    "video.soon": "Coming soon",
    "video.ready": "Introduction video",
    "video.pending": "My introduction video will be here. Until then, you can explore my experience below.",
    "video.description": "How I see communication, what drives me and what I can bring to your next project. In my own words.",
    "video.play": "Watch introduction",
    "video.title": "Meet SARA",
    "video.error": "The video could not be loaded. Please try again later.",
    "new.experienceHeading1": "Where I’ve",
    "new.experienceHeading2": "worked",
    "new.experienceIntro": "Accounts, content, media and events. These are the teams I have been part of.",
    "new.roleSanno": "Communications Assistant",
    "new.roleParadigma": "Junior Account Executive",
    "new.roleTicket": "Accreditation Management",
    "new.roleEnglish": "English Teacher",
    "new.jobOlixir": "Healthcare project management, briefing coordination, materials and presentations, administrative and financial management, and support reviewing healthcare content.",
    "new.jobSanno": "Social media and newsletter content creation and planning, materials and presentations, collaborator outreach, event support and market analysis.",
    "new.jobLewis": "Media outreach, opinion articles and social media content, project organisation and management, and administrative support.",
    "new.jobParadigma": "Receiving briefs, healthcare account management, project supervision and logistics management.",
    "new.jobTicket": "Coordinating the accreditation team for the VIP section at Palau Sant Jordi.",
    "new.jobDiari": "Weekly content planning and social media coordination.",
    "new.jobEnglish": "Planning and coordinating activities, caring for children aged 4 to 8 and administrative organisation.",
    "new.educationHeading1": "What I’ve",
    "new.educationHeading2": "studied",
    "new.courseProtocol": "Protocol and Communication",
    "new.courseVideo": "Audiovisual Production for Social Media",
    "new.skillsHeading": "My tools",
    "new.skillStrategy": "Organisation",
    "new.skillStrategyText": "Project management, team coordination, attention to detail and problem solving.",
    "new.skillCreative": "Design and content",
    "new.skillCommunication": "Communication",
    "new.skillCommunicationText": "Public speaking, media relations, teamwork and content creation.",
    "new.contactHeading1": "Let’s talk",
    "new.contactHeading2": "Write to me",
    "new.backTop": "Back to top"
  },
  "fr": {
    "new.creativeNote": "Idées, notes et travail quotidien",
    "ui.skip": "Aller au contenu",
    "ui.language": "Langue",
    "ui.appearance": "Apparence",
    "ui.light": "Clair",
    "ui.dark": "Sombre",
    "ui.close": "Fermer la vidéo",
    "new.letsTalk": "Parlons-en",
    "new.discipline": "PUBLICITÉ / RELATIONS PUBLIQUES",
    "new.heroText": "Diplômée de l’UPF. J’ai travaillé en gestion de comptes, communication et contenu, notamment dans le secteur de la santé.",
    "new.meet": "Découvrez-moi",
    "new.heroFooter": "Barcelone / Publicité et communication",
    "new.scroll": "Continuez à explorer",
    "new.aboutHeading1": "Un peu",
    "new.aboutHeading2": "sur moi",
    "new.aboutLead": "J’ai travaillé en agence, en équipe de communication et dans l’événementiel. Chaque poste m’a appris quelque chose de différent.",
    "new.aboutText": "Diplômée en Publicité et Relations Publiques de l’Universitat Pompeu Fabra, j’ai travaillé en communication de santé, relations presse, réseaux sociaux et coordination d’événements.",
    "new.aboutPersonal": "Mon expérience va de la préparation de présentations et de la coordination de briefs à la rédaction pour les réseaux sociaux et aux relations presse. J’aime travailler avec les autres et soigner les détails de chaque livraison.",
    "new.presentation": "Avec mes propres mots",
    "new.videoEyebrow": "PRÉSENTATION",
    "new.videoHeading1": "Bonjour,",
    "new.videoHeading2": "je suis Sara",
    "new.discover": "Découvrez mon expérience",
    "video.soon": "Bientôt",
    "video.ready": "Vidéo de présentation",
    "video.pending": "Ma vidéo de présentation sera ici. En attendant, découvrez mon expérience ci-dessous.",
    "video.description": "Ma vision de la communication, ce qui me motive et ce que je peux apporter à votre prochain projet. Avec mes propres mots.",
    "video.play": "Voir la présentation",
    "video.title": "Présentation de SARA",
    "video.error": "La vidéo n’a pas pu être chargée. Réessayez plus tard.",
    "new.experienceHeading1": "Mon",
    "new.experienceHeading2": "parcours",
    "new.experienceIntro": "Comptes, contenus, médias et événements. Voici les équipes dont j’ai fait partie.",
    "new.roleSanno": "Assistante de Communication",
    "new.roleParadigma": "Chargée de Clientèle Junior",
    "new.roleTicket": "Gestion des accréditations",
    "new.roleEnglish": "Professeure d’anglais",
    "new.jobOlixir": "Gestion de projets dans le secteur de la santé, coordination des briefs, création de supports et présentations, gestion administrative et financière et aide à la révision des contenus de santé.",
    "new.jobSanno": "Création et planification de contenus pour les réseaux sociaux et la newsletter, supports et présentations, contact avec les collaborateurs, aide aux événements et analyse du marché.",
    "new.jobLewis": "Relations avec les médias, rédaction d’articles d’opinion et de contenus pour les réseaux sociaux, organisation et gestion de projets et gestion administrative.",
    "new.jobParadigma": "Réception de briefs, gestion de comptes dans le secteur de la santé, supervision de projets et gestion logistique.",
    "new.jobTicket": "Coordination de l’équipe d’accréditation de la section VIP au Palau Sant Jordi.",
    "new.jobDiari": "Planification hebdomadaire des contenus et coordination des réseaux sociaux.",
    "new.jobEnglish": "Planification et coordination d’activités, garde d’enfants de 4 à 8 ans et organisation administrative.",
    "new.educationHeading1": "Mes",
    "new.educationHeading2": "études",
    "new.courseProtocol": "Protocole et Communication",
    "new.courseVideo": "Réalisation Audiovisuelle pour les Réseaux Sociaux",
    "new.skillsHeading": "Mes outils",
    "new.skillStrategy": "Organisation",
    "new.skillStrategyText": "Gestion de projets, coordination d’équipes, souci du détail et résolution de problèmes.",
    "new.skillCreative": "Design et contenu",
    "new.skillCommunication": "Communication",
    "new.skillCommunicationText": "Prise de parole, relations médias, travail en équipe et création de contenus.",
    "new.contactHeading1": "On en parle ?",
    "new.contactHeading2": "Écrivez-moi",
    "new.backTop": "Retour en haut"
  },
  "de": {
    "new.creativeNote": "Ideen, Notizen und tägliche Arbeit",
    "ui.skip": "Zum Inhalt springen",
    "ui.language": "Sprache",
    "ui.appearance": "Darstellung",
    "ui.light": "Hell",
    "ui.dark": "Dunkel",
    "ui.close": "Video schließen",
    "new.letsTalk": "Lass uns reden",
    "new.discipline": "WERBUNG / PUBLIC RELATIONS",
    "new.heroText": "UPF-Absolventin. Ich habe in Kundenbetreuung, Kommunikation und Content gearbeitet, besonders im Gesundheitsbereich.",
    "new.meet": "Lerne mich kennen",
    "new.heroFooter": "Barcelona / Werbung und Kommunikation",
    "new.scroll": "Weiter entdecken",
    "new.aboutHeading1": "Ein wenig",
    "new.aboutHeading2": "über mich",
    "new.aboutLead": "Ich habe in Agenturen, Kommunikationsteams und bei Veranstaltungen gearbeitet. Jede Stelle hat mir etwas anderes beigebracht.",
    "new.aboutText": "Ich habe Werbung und Public Relations an der Universitat Pompeu Fabra studiert. Meine Erfahrung umfasst Gesundheitskommunikation, Medienarbeit, Social Media und Veranstaltungskoordination.",
    "new.aboutPersonal": "Meine Erfahrung reicht von Präsentationen und der Koordination von Briefings bis zu Social-Media-Texten und Medienkontakten. Ich arbeite gern mit anderen zusammen und achte bei jeder Aufgabe auf die Details.",
    "new.presentation": "In meinen eigenen Worten",
    "new.videoEyebrow": "VORSTELLUNG",
    "new.videoHeading1": "Hallo,",
    "new.videoHeading2": "ich bin Sara",
    "new.discover": "Entdecke meine Erfahrung",
    "video.soon": "Demnächst",
    "video.ready": "Vorstellungsvideo",
    "video.pending": "Hier wird mein Vorstellungsvideo stehen. Bis dahin findest du meine Erfahrung weiter unten.",
    "video.description": "Mein Blick auf Kommunikation, was mich antreibt und was ich zu deinem nächsten Projekt beitragen kann. In meinen eigenen Worten.",
    "video.play": "Vorstellung ansehen",
    "video.title": "SARA stellt sich vor",
    "video.error": "Das Video konnte nicht geladen werden. Bitte versuche es später erneut.",
    "new.experienceHeading1": "Meine",
    "new.experienceHeading2": "Stationen",
    "new.experienceIntro": "Kundenbetreuung, Content, Medien und Veranstaltungen. In diesen Teams habe ich gearbeitet.",
    "new.roleSanno": "Kommunikationsassistentin",
    "new.roleParadigma": "Junior Account Executive",
    "new.roleTicket": "Akkreditierungsmanagement",
    "new.roleEnglish": "Englischlehrerin",
    "new.jobOlixir": "Projektmanagement im Gesundheitswesen, Koordination von Briefings, Erstellung von Materialien und Präsentationen, administrative und finanzielle Verwaltung sowie Unterstützung bei der Prüfung medizinischer Inhalte.",
    "new.jobSanno": "Erstellung und Planung von Social-Media- und Newsletter-Inhalten, Materialien und Präsentationen, Kontakt mit Partnern, Veranstaltungsunterstützung und Marktanalyse.",
    "new.jobLewis": "Medienkontakt, Meinungsartikel und Social-Media-Inhalte, Projektorganisation und -management sowie administrative Verwaltung.",
    "new.jobParadigma": "Entgegennahme von Briefings, Kundenbetreuung im Gesundheitswesen, Projektbetreuung und Logistikmanagement.",
    "new.jobTicket": "Koordination des Akkreditierungsteams für den VIP-Bereich im Palau Sant Jordi.",
    "new.jobDiari": "Wöchentliche Inhaltsplanung und Social-Media-Koordination.",
    "new.jobEnglish": "Planung und Koordination von Aktivitäten, Betreuung von Kindern zwischen 4 und 8 Jahren und administrative Organisation.",
    "new.educationHeading1": "Meine",
    "new.educationHeading2": "Ausbildung",
    "new.courseProtocol": "Protokoll und Kommunikation",
    "new.courseVideo": "Audiovisuelle Produktion für Social Media",
    "new.skillsHeading": "Meine Werkzeuge",
    "new.skillStrategy": "Organisation",
    "new.skillStrategyText": "Projektmanagement, Teamkoordination, Liebe zum Detail und Problemlösung.",
    "new.skillCreative": "Design und Content",
    "new.skillCommunication": "Kommunikation",
    "new.skillCommunicationText": "Rhetorik, Medienarbeit, Teamarbeit und Inhaltserstellung.",
    "new.contactHeading1": "Sprechen wir?",
    "new.contactHeading2": "Schreib mir",
    "new.backTop": "Nach oben"
  }
};
